const abi = [
  {
     "constant":true,
     "inputs":[

     ],
     "name":"mintingFinished",
     "outputs":[
        {
           "name":"",
           "type":"bool"
        }
     ],
     "payable":false,
     "stateMutability":"view",
     "type":"function"
  },
  {
     "constant":false,
     "inputs":[
        {
           "name":"_spender",
           "type":"address"
        },
        {
           "name":"_amount",
           "type":"uint256"
        }
     ],
     "name":"approve",
     "outputs":[
        {
           "name":"",
           "type":"bool"
        }
     ],
     "payable":false,
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "constant":true,
     "inputs":[

     ],
     "name":"totalSupply",
     "outputs":[
        {
           "name":"totalAmount",
           "type":"uint256"
        }
     ],
     "payable":false,
     "stateMutability":"view",
     "type":"function"
  },
  {
     "constant":false,
     "inputs":[
        {
           "name":"_from",
           "type":"address"
        },
        {
           "name":"_to",
           "type":"address"
        },
        {
           "name":"_amount",
           "type":"uint256"
        }
     ],
     "name":"transferFrom",
     "outputs":[
        {
           "name":"success",
           "type":"bool"
        }
     ],
     "payable":false,
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "constant":true,
     "inputs":[

     ],
     "name":"DECIMALS",
     "outputs":[
        {
           "name":"",
           "type":"uint8"
        }
     ],
     "payable":false,
     "stateMutability":"view",
     "type":"function"
  },
  {
     "constant":false,
     "inputs":[
        {
           "name":"_to",
           "type":"address"
        },
        {
           "name":"_amount",
           "type":"uint256"
        }
     ],
     "name":"mint",
     "outputs":[
        {
           "name":"",
           "type":"bool"
        }
     ],
     "payable":false,
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "constant":true,
     "inputs":[
        {
           "name":"_address",
           "type":"address"
        }
     ],
     "name":"balanceOf",
     "outputs":[
        {
           "name":"balance",
           "type":"uint256"
        }
     ],
     "payable":false,
     "stateMutability":"view",
     "type":"function"
  },
  {
     "constant":false,
     "inputs":[

     ],
     "name":"finishMinting",
     "outputs":[
        {
           "name":"",
           "type":"bool"
        }
     ],
     "payable":false,
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "constant":true,
     "inputs":[

     ],
     "name":"baseSupply",
     "outputs":[
        {
           "name":"initialAmount",
           "type":"uint256"
        }
     ],
     "payable":false,
     "stateMutability":"view",
     "type":"function"
  },
  {
     "constant":true,
     "inputs":[

     ],
     "name":"owner",
     "outputs":[
        {
           "name":"",
           "type":"address"
        }
     ],
     "payable":false,
     "stateMutability":"view",
     "type":"function"
  },
  {
     "constant":true,
     "inputs":[

     ],
     "name":"NAME",
     "outputs":[
        {
           "name":"",
           "type":"string"
        }
     ],
     "payable":false,
     "stateMutability":"view",
     "type":"function"
  },
  {
     "constant":false,
     "inputs":[
        {
           "name":"_to",
           "type":"address"
        },
        {
           "name":"_amount",
           "type":"uint256"
        }
     ],
     "name":"transfer",
     "outputs":[
        {
           "name":"",
           "type":"bool"
        }
     ],
     "payable":false,
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "constant":false,
     "inputs":[

     ],
     "name":"makeTradable",
     "outputs":[

     ],
     "payable":false,
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "constant":true,
     "inputs":[
        {
           "name":"_owner",
           "type":"address"
        },
        {
           "name":"_spender",
           "type":"address"
        }
     ],
     "name":"allowance",
     "outputs":[
        {
           "name":"remaining",
           "type":"uint256"
        }
     ],
     "payable":false,
     "stateMutability":"view",
     "type":"function"
  },
  {
     "constant":false,
     "inputs":[
        {
           "name":"_newOwner",
           "type":"address"
        }
     ],
     "name":"transferOwnership",
     "outputs":[

     ],
     "payable":false,
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "constant":true,
     "inputs":[

     ],
     "name":"SYMBOL",
     "outputs":[
        {
           "name":"",
           "type":"string"
        }
     ],
     "payable":false,
     "stateMutability":"view",
     "type":"function"
  },
  {
     "constant":true,
     "inputs":[

     ],
     "name":"vault",
     "outputs":[
        {
           "name":"",
           "type":"address"
        }
     ],
     "payable":false,
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[

     ],
     "payable":false,
     "stateMutability":"nonpayable",
     "type":"constructor"
  },
  {
     "anonymous":false,
     "inputs":[
        {
           "indexed":true,
           "name":"_to",
           "type":"address"
        },
        {
           "indexed":false,
           "name":"_value",
           "type":"uint256"
        }
     ],
     "name":"Mint",
     "type":"event"
  },
  {
     "anonymous":false,
     "inputs":[

     ],
     "name":"MintFinished",
     "type":"event"
  },
  {
     "anonymous":false,
     "inputs":[

     ],
     "name":"TradableTokens",
     "type":"event"
  },
  {
     "anonymous":false,
     "inputs":[
        {
           "indexed":true,
           "name":"_from",
           "type":"address"
        },
        {
           "indexed":true,
           "name":"_to",
           "type":"address"
        },
        {
           "indexed":false,
           "name":"_amount",
           "type":"uint256"
        }
     ],
     "name":"Transfer",
     "type":"event"
  },
  {
     "anonymous":false,
     "inputs":[
        {
           "indexed":true,
           "name":"_owner",
           "type":"address"
        },
        {
           "indexed":true,
           "name":"_spender",
           "type":"address"
        },
        {
           "indexed":false,
           "name":"_amount",
           "type":"uint256"
        }
     ],
     "name":"Approval",
     "type":"event"
  }
];

const contract = web3.eth.contract(abi).at('0xc77add231ef94ca78968aa6ce7e4f4474362c544');

export default
{
  getBalance()
  {
    return new Promise((resolve, reject) =>
    {
      contract.balanceOf(web3.eth.defaultAccount, function(error, balance)
      {
        if(error)
        {
          return reject(error);
        }
        resolve(balance);
      });
    });
  },
  transfer()
  {
    return new Promise((resolve, reject) =>
    {
      contract.transfer(web3.eth.defaultAccount, 1, {value: 0, gas: 2000}, function(error, balance)
      {
        if(error)
        {
          return reject(error);
        }
        resolve(balance);
      });
    });
  }
}

// create filter
// var filter = myContractInstance.myEvent({a: 5}, function (error, result) {
//   if (!error)
//     console.log(result);
//     /*
//     {
//         address: '0x8718986382264244252fc4abd0339eb8d5708727',
//         topics: "0x12345678901234567890123456789012", "0x0000000000000000000000000000000000000000000000000000000000000005",
//         data: "0x0000000000000000000000000000000000000000000000000000000000000001",
//         ...
//     }
//     */
// });